### ISSUE TITLE
Customize Pipeline Statement wipes file clean

### ISSUE THREAD

**Issue by slipsibm** [mq-modernization-demo/mq01-src#1]
In the Customize Pipeline Section -> https://github.com/mq-modernization-demo/mq01-src#customize-pipeline this statement wipes out the file so there is nothing to run in the next step
`envsubst <mq-dev-pipelinerun.yaml > mq-dev-pipelinerun.yaml` 

I see several Google references that suggest that rewriting a file with envsubst can wipe the file but I don't know if it is distribution based or what. The recommendation is to write the file to a temp file to make sure its saved properly. I'm running RHEL 8.8. 

Since the next step is to run the yaml anyway, I ran the following command instead:
`envsubst <mq-dev-pipelinerun.yaml | oc create -f -`

**Comment by ODOWDAIBM** [comment]
Fixed this with proper use of temporary files.
