### ISSUE TITLE
Mismatch in names of yaml in pipeline

### ISSUE THREAD

**Issue by slipsibm** [mq-modernization-demo/mq01-src#2]
In mq01-src/xbuild/pipeline/mq-gen-yamls.yaml the references to the qmgr and cert are wrong so they never get copied over
This:

cp config/yamls/mq01.yaml yamls/.
cp config/yamls/mq01-ingress.yaml yamls/.`

should be:

 cp config/yamls/mq01-qmgr.yaml yamls/.
 cp config/yamls/mq01-cert.yaml yamls/.

**Comment by ODOWDAIBM** [comment]
Fixed!
