### ISSUE TITLE
mq01-qmgr.yaml has reference to lvms-vg1 for default storage class

### ISSUE THREAD

**Issue by slipsibm** [mq-modernization-demo/mq01-src#3]
config/yamls/mq01-qmgr.yaml has a reference to lvms-vg1 for the storage call which won't work if that storage class doesn't exist

If you leave defaultClass: blank it seems to pick up the default storage class of the cluster. 

Maybe a discussion about this in the readme that there are several ways to handle:

- that changing the default storage class to one supported by MQ by adding an annotation to a storage class and removing the annotation from the existing default if one exists:  

              `storageclass.kubernetes.io/is-default-class=true`

- or just having them edit the file to point to a valid class , 
we could also handle it via an environment variable

**Comment by ODOWDAIBM** [comment]
I updated the qmgr YAML to `storageClass:` (effectively null) which picks up the default storage class!
